- name: Install Java 
  package:
    name: java 
    state: installed 

- name: Install Logstash 
  package:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-{{VERSION}}.rpm
    state: installed 

- name: Start Logstash 
  service:
    name: logstash 
    enabled: yes 
    state: started 